import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { GlobalBackground } from "@/components/GlobalBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-white selection:bg-indigo-500/30`}
        suppressHydrationWarning
      >
        <GlobalBackground />
        <div className="relative z-10">
          {children}
        </div>
        <Analytics />
        <SpeedInsights />
        <script src="https://code.iconify.design/iconify-icon/1.0.8/iconify-icon.min.js"></script>
      </body>
    </html>
  );
}
